plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.u7e5f3218e9'
    compileSdk 34

    defaultConfig {
        applicationId "com.example.u7e5f3218e9"
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName "1.1"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    // 该工程仅使用原生 Android 框架 API，无第三方依赖
}